apiVersion: v1
kind: Service
metadata:
  name: db
  labels:
    name: postgres-services
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - port: 5372
      targetPort: 5372
  selector:
    name: postgres-pod
    app: demo-voting-app
      

